[package]
name = "pacwrap-core"
description = "Library providing core functionality for pacwrap"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

homepage.workspace = true
repository.workspace = true

[dependencies]
bitflags = "2.4"
nix = "0.22.3, <= 0.22.3"
time = { version = "0.3.28", features = ["formatting", "macros", "local-offset", "parsing"] }
indexmap = { version = "2.0.0", features = ["serde", "rayon"] }
simplebyteunit.workspace = true
walkdir = "2.3"

# Serialization
serde = { version = "1.0", features = ["derive", "rc"] }
serde_yaml = "0.9.33, <= 0.9.33"
typetag="0.2"
dyn-clone = "1.0"
bincode = "1.3.3"

#Container runtime
command-fds = "0.2.2"
os_pipe = "1.1.4"
libseccomp = "0.4"
signal-hook = "0.3"

# Packaging
pacmanconf = "3.0"
tar = "0.4"
zstd = "0.13"

# Threading
rayon = "1.7"

# CLI libraries
dialoguer = "0.10.4"
indicatif = "0.18"

#Cryptography
sha2 = "0.10"
serde_with = "3.11"
postcard = { version="1.1.3", features = ["alloc"] }

[dependencies.alpm]
workspace = true
