[workspace]
resolver = "2"
members = ["pacwrap", "pacwrap-agent", "pacwrap-core"]

[workspace.package]
version = "0.9.0-alpha1"
edition = "2024"
rust-version = "1.85"
readme = "README.md"

license = "GPL-3.0-only"
authors = [ "Xavier Moffett <sapphirus@azorium.net>" ]
keywords = [ "bubblewrap", "sandbox", "package", "manager", "archlinux" ]
categories = [ "command-line-utilities", "virtualization", "filesystem", "concurrency", "caching" ]

homepage = "https://pacwrap.sapphirus.org/"
repository = "https://github.com/pacwrap/pacwrap"

[workspace.dependencies]
pacwrap-core = { version = "0.9.0-alpha1", path = "pacwrap-core" }
alpm = { version = "5.0.0", features = ["checkver"] }
indexmap = { version = "2.0.0", features = ["serde", "rayon"] }
simplebyteunit = "0.3.0"
walkdir = "2.3"
thiserror = "2.0"
anyhow = "1.0"
rayon = "1.11.0"

[profile.release]
lto = "thin"
opt-level = "s"
