# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "pacwrap"
version = "0.1.2"
edition = "2021"

[dependencies]
command-fds = "0.2.2"
#tempfile = "3"
serde_json = "1.0"
envy = "0.4"
nix = "0.26.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
typetag="0.2"
os_pipe = "1.1.4"
signal-hook = "0.3.15"

[profile.release]
lto = "thin"
opt-level = "s"
