[package]
name = "pacwrap-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpm = { version = "2.2.2", features = ["checkver"] }
pacwrap-lib = { path = "../pacwrap-lib/", version = "0.4.4" }
serde = { version = "1.0", features = ["derive"] }
ciborium = "0.2.1"
