[package]
name = "pacwrap-agent"
version = "0.6.0"
authors = [ "Xavier R.M. <sapphirus@azorium.net>" ]
license ="GPL-3.0-only"
readme = "README.md"
edition = "2021"

description = "Executable agent for conducting containerized transactions"
homepage = "https://pacwrap.sapphirus.org/"
repository = "https://git.sapphirus.org/pacwrap/pacwrap"

[dependencies]
pacwrap-core = { path = "../pacwrap-core", version = "0.6.0" }

# Serialization
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"

# Packaging
alpm = { version = "2.2.2", features = ["checkver"] }
