[package]
name = "pacwrap-agent"
version = "0.7.2"
authors = [ "Xavier R.M. <sapphirus@azorium.net>" ]
license ="GPL-3.0-only"
readme = "README.md"
edition = "2021"

description = "Executable agent for conducting containerized transactions"
homepage = "https://pacwrap.sapphirus.org/"
repository = "https://github.com/pacwrap/pacwrap"

[dependencies]
pacwrap-core = { path = "../pacwrap-core", version = "0.7.2" }

# Serialization
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"

# Packaging
alpm = { version = "3.0.5", features = ["checkver"] }
