name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

env: 
  PACWRAP_SCHEMA_BUILT: 1
  PACWRAP_CI: 1

jobs:
  format:
    name: Format
    runs-on: vm-runner-xs
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup update ${{ matrix.toolchain }}
      - name: Check format
        run: cargo fmt --check
  lint:
    name: Lint
    runs-on: vm-runner
    strategy:
      matrix:
        toolchain:
          - stable
    env: 
      PACWRAP_SCHEMA_BUILT: 0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup update ${{ matrix.toolchain }}
      - name: Initialize cache
        uses: actions/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Lint
        run: cargo clippy --release -- -Dwarnings
  build:
    name: Build
    runs-on: vm-runner
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo pacman -Syu --needed --noconfirm \
            bubblewrap \
            fakeroot \
            fakechroot \
            busybox
      - name: Install toolchain
        run: rustup update ${{ matrix.toolchain }}
      - name: Initialize cache
        uses: actions/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build pacwrap
        run: |
          ./dist/tools/prepare.sh release \
            && cargo build --release \
            && ./dist/tools/package.sh release
