# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "pacwrap"
version = "0.5.0"
edition = "2021"
default-run = "pacwrap"

[dependencies]
pacwrap-core = { path = "../pacwrap-core/", version = "0.5.0" }
command-fds = "0.2.2"
serde_json = "1.0"
nix = "0.22.3, <= 0.22.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_yaml = "0.9"
os_pipe = "1.1.4"
signal-hook = "0.3.15"
lazy_static = "1.4.0"
alpm = { version = "2.2.2", features = ["checkver"] }
indexmap = { version = "2.0.0", features = ["serde", "rayon"] }
